/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface AgreementInterface extends utils.Interface {
  functions: {
    "agreementId()": FunctionFragment;
    "cancelAgreement()": FunctionFragment;
    "cid()": FunctionFragment;
    "deadline()": FunctionFragment;
    "fulfillRequest(bytes32,bytes32)": FunctionFragment;
    "js()": FunctionFragment;
    "onTokenTransfer(address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "priVars()": FunctionFragment;
    "pubVars()": FunctionFragment;
    "recoverFunds()": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "soulbound()": FunctionFragment;
    "state()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "agreementId"
      | "cancelAgreement"
      | "cid"
      | "deadline"
      | "fulfillRequest"
      | "js"
      | "onTokenTransfer"
      | "owner"
      | "priVars"
      | "pubVars"
      | "recoverFunds"
      | "setOwner"
      | "soulbound"
      | "state"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "agreementId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAgreement",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cid", values?: undefined): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fulfillRequest",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "js", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onTokenTransfer",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "priVars", values?: undefined): string;
  encodeFunctionData(functionFragment: "pubVars", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recoverFunds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(functionFragment: "soulbound", values?: undefined): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "agreementId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "js", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priVars", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pubVars", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "soulbound", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;

  events: {
    "Filled(uint256)": EventFragment;
    "OwnerUpdated(address,address)": EventFragment;
    "Received(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Filled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Received"): EventFragment;
}

export interface FilledEventObject {
  result: BigNumber;
}
export type FilledEvent = TypedEvent<[BigNumber], FilledEventObject>;

export type FilledEventFilter = TypedEventFilter<FilledEvent>;

export interface OwnerUpdatedEventObject {
  user: string;
  newOwner: string;
}
export type OwnerUpdatedEvent = TypedEvent<
  [string, string],
  OwnerUpdatedEventObject
>;

export type OwnerUpdatedEventFilter = TypedEventFilter<OwnerUpdatedEvent>;

export interface ReceivedEventObject {
  arg0: string;
  arg1: BigNumber;
}
export type ReceivedEvent = TypedEvent<
  [string, BigNumber],
  ReceivedEventObject
>;

export type ReceivedEventFilter = TypedEventFilter<ReceivedEvent>;

export interface Agreement extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AgreementInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    agreementId(overrides?: CallOverrides): Promise<[BigNumber]>;

    cancelAgreement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cid(overrides?: CallOverrides): Promise<[string]>;

    deadline(overrides?: CallOverrides): Promise<[BigNumber]>;

    fulfillRequest(
      arg0: BytesLike,
      _result: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    js(overrides?: CallOverrides): Promise<[string]>;

    onTokenTransfer(
      sender: string,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    priVars(overrides?: CallOverrides): Promise<[string]>;

    pubVars(overrides?: CallOverrides): Promise<[string]>;

    recoverFunds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    soulbound(overrides?: CallOverrides): Promise<[boolean]>;

    state(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _state: BigNumber }>;
  };

  agreementId(overrides?: CallOverrides): Promise<BigNumber>;

  cancelAgreement(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cid(overrides?: CallOverrides): Promise<string>;

  deadline(overrides?: CallOverrides): Promise<BigNumber>;

  fulfillRequest(
    arg0: BytesLike,
    _result: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  js(overrides?: CallOverrides): Promise<string>;

  onTokenTransfer(
    sender: string,
    amount: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  priVars(overrides?: CallOverrides): Promise<string>;

  pubVars(overrides?: CallOverrides): Promise<string>;

  recoverFunds(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  soulbound(overrides?: CallOverrides): Promise<boolean>;

  state(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    agreementId(overrides?: CallOverrides): Promise<BigNumber>;

    cancelAgreement(overrides?: CallOverrides): Promise<void>;

    cid(overrides?: CallOverrides): Promise<string>;

    deadline(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillRequest(
      arg0: BytesLike,
      _result: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    js(overrides?: CallOverrides): Promise<string>;

    onTokenTransfer(
      sender: string,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    priVars(overrides?: CallOverrides): Promise<string>;

    pubVars(overrides?: CallOverrides): Promise<string>;

    recoverFunds(overrides?: CallOverrides): Promise<void>;

    setOwner(newOwner: string, overrides?: CallOverrides): Promise<void>;

    soulbound(overrides?: CallOverrides): Promise<boolean>;

    state(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Filled(uint256)"(result?: null): FilledEventFilter;
    Filled(result?: null): FilledEventFilter;

    "OwnerUpdated(address,address)"(
      user?: string | null,
      newOwner?: string | null
    ): OwnerUpdatedEventFilter;
    OwnerUpdated(
      user?: string | null,
      newOwner?: string | null
    ): OwnerUpdatedEventFilter;

    "Received(address,uint256)"(arg0?: null, arg1?: null): ReceivedEventFilter;
    Received(arg0?: null, arg1?: null): ReceivedEventFilter;
  };

  estimateGas: {
    agreementId(overrides?: CallOverrides): Promise<BigNumber>;

    cancelAgreement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cid(overrides?: CallOverrides): Promise<BigNumber>;

    deadline(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillRequest(
      arg0: BytesLike,
      _result: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    js(overrides?: CallOverrides): Promise<BigNumber>;

    onTokenTransfer(
      sender: string,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    priVars(overrides?: CallOverrides): Promise<BigNumber>;

    pubVars(overrides?: CallOverrides): Promise<BigNumber>;

    recoverFunds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    soulbound(overrides?: CallOverrides): Promise<BigNumber>;

    state(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    agreementId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelAgreement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cid(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deadline(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fulfillRequest(
      arg0: BytesLike,
      _result: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    js(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onTokenTransfer(
      sender: string,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priVars(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pubVars(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recoverFunds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    soulbound(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    state(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
