/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as offerRegistrySol from "./OfferRegistry.sol";
export type { offerRegistrySol };
import type * as requesterSol from "./Requester.sol";
export type { requesterSol };
export type { AggregatorOperator } from "./AggregatorOperator";
export type { DirectRequestAggregator } from "./DirectRequestAggregator";
