/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as requesterSol from "./Requester.sol";
export type { requesterSol };
export type { OfferRegistry } from "./OfferRegistry";
