/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  RequesterInterface,
  RequesterInterfaceInterface,
} from "../../../contracts/OfferRegistry.sol/RequesterInterface";

const _abi = [
  {
    inputs: [],
    name: "getState",
    outputs: [
      {
        internalType: "bytes32",
        name: "state",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class RequesterInterface__factory {
  static readonly abi = _abi;
  static createInterface(): RequesterInterfaceInterface {
    return new utils.Interface(_abi) as RequesterInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RequesterInterface {
    return new Contract(address, _abi, signerOrProvider) as RequesterInterface;
  }
}
