/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OfferRegistry } from "./OfferRegistry";
export type { RequesterInterface } from "./RequesterInterface";
