[default]
src = 'src'
out = 'artifacts'
libs = [
    'lib',
    'node_modules',
]
test = 'test/foundry'
script = 'scripts/foundry'
cache_path  = 'forge-cache'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config