/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgreement } from "./IAgreement";
export type { IUniversalAdapter } from "./IUniversalAdapter";
