/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  LinkTokenReceiver,
  LinkTokenReceiverInterface,
} from "../../../../../@chainlink/contracts/src/v0.7/LinkTokenReceiver";

const _abi = [
  {
    inputs: [],
    name: "getChainlinkToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onTokenTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class LinkTokenReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): LinkTokenReceiverInterface {
    return new utils.Interface(_abi) as LinkTokenReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LinkTokenReceiver {
    return new Contract(address, _abi, signerOrProvider) as LinkTokenReceiver;
  }
}
