/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface UniversalAdapterInterfaceInterface extends utils.Interface {
  functions: {
    "makeRequest(bytes4,string,string,string,string)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "makeRequest"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "makeRequest",
    values: [BytesLike, string, string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "makeRequest",
    data: BytesLike
  ): Result;

  events: {};
}

export interface UniversalAdapterInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniversalAdapterInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    makeRequest(
      callbackFunctionId: BytesLike,
      js: string,
      cid: string,
      vars: string,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  makeRequest(
    callbackFunctionId: BytesLike,
    js: string,
    cid: string,
    vars: string,
    ref: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    makeRequest(
      callbackFunctionId: BytesLike,
      js: string,
      cid: string,
      vars: string,
      ref: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    makeRequest(
      callbackFunctionId: BytesLike,
      js: string,
      cid: string,
      vars: string,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    makeRequest(
      callbackFunctionId: BytesLike,
      js: string,
      cid: string,
      vars: string,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
