/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as requesterSol from "./Requester.sol";
export { UniversalAdapter__factory } from "./UniversalAdapter__factory";
