/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAgreement,
  IAgreementInterface,
} from "../../../contracts/interfaces/IAgreement";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_result",
        type: "bytes32",
      },
    ],
    name: "fulfillRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_vars",
        type: "string",
      },
    ],
    name: "makeRequest",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAgreement__factory {
  static readonly abi = _abi;
  static createInterface(): IAgreementInterface {
    return new utils.Interface(_abi) as IAgreementInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAgreement {
    return new Contract(address, _abi, signerOrProvider) as IAgreement;
  }
}
