/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUniversalAdapter,
  IUniversalAdapterInterface,
} from "../../../contracts/interfaces/IUniversalAdapter";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "callbackFunctionId",
        type: "bytes4",
      },
      {
        internalType: "string",
        name: "js",
        type: "string",
      },
      {
        internalType: "string",
        name: "cid",
        type: "string",
      },
      {
        internalType: "string",
        name: "vars",
        type: "string",
      },
      {
        internalType: "string",
        name: "ref",
        type: "string",
      },
    ],
    name: "makeRequest",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IUniversalAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): IUniversalAdapterInterface {
    return new utils.Interface(_abi) as IUniversalAdapterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniversalAdapter {
    return new Contract(address, _abi, signerOrProvider) as IUniversalAdapter;
  }
}
