/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DirectRequestAggregatorInterface,
  DirectRequestAggregatorInterfaceInterface,
} from "../../../contracts/Requester.sol/DirectRequestAggregatorInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "js",
        type: "string",
      },
      {
        internalType: "string",
        name: "cid",
        type: "string",
      },
      {
        internalType: "string",
        name: "vars",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "ref",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "returnType",
        type: "bytes32",
      },
    ],
    name: "makeRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class DirectRequestAggregatorInterface__factory {
  static readonly abi = _abi;
  static createInterface(): DirectRequestAggregatorInterfaceInterface {
    return new utils.Interface(
      _abi
    ) as DirectRequestAggregatorInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DirectRequestAggregatorInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DirectRequestAggregatorInterface;
  }
}
