/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  UniversalAdapterInterface,
  UniversalAdapterInterfaceInterface,
} from "../../../contracts/Requester.sol/UniversalAdapterInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "callbackFunctionId",
        type: "bytes4",
      },
      {
        internalType: "string",
        name: "js",
        type: "string",
      },
      {
        internalType: "string",
        name: "cid",
        type: "string",
      },
      {
        internalType: "string",
        name: "vars",
        type: "string",
      },
      {
        internalType: "string",
        name: "ref",
        type: "string",
      },
    ],
    name: "makeRequest",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class UniversalAdapterInterface__factory {
  static readonly abi = _abi;
  static createInterface(): UniversalAdapterInterfaceInterface {
    return new utils.Interface(_abi) as UniversalAdapterInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UniversalAdapterInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as UniversalAdapterInterface;
  }
}
