/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DirectRequestAggregatorInterface } from "./DirectRequestAggregatorInterface";
export type { ExampleRequester } from "./ExampleRequester";
