/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "LinkTokenInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LinkTokenInterface__factory>;
    getContractFactory(
      name: "DirectRequestAggregatorInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DirectRequestAggregatorInterface__factory>;
    getContractFactory(
      name: "OfferRegistryInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OfferRegistryInterface__factory>;
    getContractFactory(
      name: "Requester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Requester__factory>;

    getContractAt(
      name: "LinkTokenInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LinkTokenInterface>;
    getContractAt(
      name: "DirectRequestAggregatorInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DirectRequestAggregatorInterface>;
    getContractAt(
      name: "OfferRegistryInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OfferRegistryInterface>;
    getContractAt(
      name: "Requester",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Requester>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
